/**
 * Centralized Security Configuration and Constants
 * Phase 13 — Production Engineering & Security
 */

const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE: 'INVALID_FILE',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SSRF_ATTEMPT_BLOCKED: 'SSRF_ATTEMPT_BLOCKED',
  CODE_EXECUTION_TIMEOUT: 'CODE_EXECUTION_TIMEOUT',
  CODE_EXECUTION_ERROR: 'CODE_EXECUTION_ERROR',
};

const PASSWORD_POLICY = {
  MIN_LENGTH: 8,
  MAX_LENGTH: 128,
  BCRYPT_SALT_ROUNDS: 10,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MS: 15 * 60 * 1000, // 15 minutes temporary throttling
};

const FILE_UPLOAD_LIMITS = {
  MAX_FILE_SIZE_BYTES: 5 * 1024 * 1024, // 5 MB
  ALLOWED_IMAGE_MIMES: ['image/jpeg', 'image/png', 'image/webp'],
  ALLOWED_DOCUMENT_MIMES: ['application/pdf'],
  ALLOWED_EXTENSIONS: ['.pdf', '.jpg', '.jpeg', '.png', '.webp'],
};

const CODE_SANDBOX_LIMITS = {
  TIMEOUT_MS: 5000,
  MAX_MEMORY_MB: 128,
  MAX_OUTPUT_LENGTH: 10000, // 10k chars
  ALLOW_NETWORK: false,
};

module.exports = {
  ERROR_CODES,
  PASSWORD_POLICY,
  FILE_UPLOAD_LIMITS,
  CODE_SANDBOX_LIMITS,
};
